# Generated by Django 3.1.4 on 2021-01-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmcode',
            options={'verbose_name': 'Код подтверждения', 'verbose_name_plural': 'Код подтверждения'},
        ),
    ]
