# Generated by Django 3.1.4 on 2021-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20210121_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmcode',
            options={'verbose_name': 'Код подтверждения', 'verbose_name_plural': 'Коды подтверждения'},
        ),
        migrations.AddField(
            model_name='confirmcode',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
