# Generated by Django 3.1.4 on 2020-12-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ex', '0002_auto_20201219_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='api_ex.Post'),
        ),
    ]
