# Generated by Django 3.1.4 on 2021-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ex', '0004_auto_20201226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post', to='api_ex.Tag'),
        ),
    ]
